# -*- coding: utf-8 -*-
ENV_DB_SERVER = 'CCS_DAL_MYSQL_DB_SERVER'
ENV_DB_USER = 'CCS_DAL_MYSQL_DB_USER'
ENV_DB_PASSWORD = 'CCS_DAL_MYSQL_DB_PASSWORD'

SQL_USER = "root"
SQL_PASSWORD = "password"
SQL_ADDR = "172.16.100.60:3306"

MODULE_ROOT = "/ccsDal"
